# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9a9d69cad38eab06c60fc63840a9ae6facb71ad0dab559ba9bd0e1a20f3e00acb1f538a2c2b6219850b642156e320b137d6e69b9d3cd77832c6ef723964ebe

test:
  secret_key_base: cb558ac3533afa56b13baa5ae8489af89f4dc7118cfd8e0e2364941379674a0bef060ae7425e4edec73e076da189203b3e886bdab2d56bc5d4d83dfaafe89527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
